### ISSUE TITLE
Clean up landing page styling

### ISSUE THREAD

**Issue by James-Lycett** [James-Lycett/workplace-wellness#15]
There are a few vestiges left over on landing page and its components from when it had a grey background which are no longer needed or even visible. GET RID OF THEM lol not that performance is an issue but I don't like computing styles that aren't used

**Comment by cozyfestiv** [comment]
Can you be more specific on this one? Do these still exist or have we gotten to them?

**Comment by James-Lycett** [comment]
Yeah I really should have been more specific cause I don't exactly remember. I think there's some places in the landing page child components (introBlock etc..) where the background color is unnecessarily assigned white and maybe some unused x-axis padding here and there

**Comment by James-Lycett** [comment]
Oh and I think I put rounded borders on some of those elements to make them look less crappy against the background but now those elements are the same color as the background so it doesn't matter if the borders are rounded or not
