### ISSUE TITLE
Links should jump to top of page

### ISSUE THREAD

**Issue by James-Lycett** [James-Lycett/workplace-wellness#16]
When I'm on whatever page and click the logo on the footer, for example, that react-router <Link/> shoots over to the landing page lightning fast which is awesome but it leaves me at the same scroll location - the bottom of the landing page. 

That feels unnatural and weird and less than desirable and should be changed, ideally without reloading the page that we're linking to cause then it isn't lightning fast anymore. Idk how to do this but I'm sure there's a way.

I'd say this needs to be done for all the footer links and maybe all the header links too, at the very least. It'd be worth navigating around the site esp once we have our other pages finished to see where else this should be changed too

**Comment by cozyfestiv** [comment]
I made this work for the footer, but I can't remember if I did it for the navbar as well.
