### ISSUE TITLE
Fill in empty links

### ISSUE THREAD

**Issue by James-Lycett** [James-Lycett/workplace-wellness#17]
There's still placeholder stuff around that could use something on the other side of it or just complete removal. The stuff in the footer especially.

Not critical just leaving this here for whenever

**Comment by cozyfestiv** [comment]
- [ ] change the color of the non active links or some sort of different formatting 
- [ ] add a link to careers to the header 
- [ ] maybe zhuzh up the boilerplate with some images or something

**Comment by James-Lycett** [comment]
Didn't do any zhuzhing, I think it's zhuzhed up enough as it is for now. If you wanna be the zhuzher you can go ahead and zhuzh your heart out, I'm pretty done with the whole zhuzhification process on this site
