### ISSUE TITLE
TAILWIND: Log Activity Page Redesign

### ISSUE THREAD

**Issue by cozyfestiv** [James-Lycett/workplace-wellness#25]

**Comment by cozyfestiv** [comment]
I just had a thought, what if this log page just came up as a pop up page, that's like floating over the other elements which are kind of blurred. You know what I mean?

**Comment by James-Lycett** [comment]
Yeah I think a little modal would work great!

**Comment by cozyfestiv** [comment]
oh right, that's what they're called made a separate issue for it
