### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by James-Lycett** [James-Lycett/workplace-wellness#37]
A few of the routes in /layout/routes.jsx are no longer going to be used and at least a couple would probably benefit from being changed to be a bit more self-explanatory.

I'm thinking "/admin/:userId/home" and "/user/:userId/home" could both be combined to be /dashboard/:userId.

**Comment by cozyfestiv** [comment]
Ok, I nested the routes for now, without changing the dashboard part quite yet. But you're right, those are duplicate routes. 

I guess I just want to make sure that you can get to the user page and back to the admin that way before I switch it over. Let's discuss this again this weekend
