### ISSUE TITLE
Update Copy where it is filler

### ISSUE THREAD

**Issue by cozyfestiv** [James-Lycett/workplace-wellness#61]
As funny as I think the homepage filler text is, I should probably replace it.

**Comment by cozyfestiv** [comment]
We think we like the silly stuff, so we're keeping it. 

Maybe just a final review to make sure there is copy everywhere it should be. 

MAYBE maybe write regular copy and comment it out in the code if you feel ambitious.

**Comment by James-Lycett** [comment]
if (dev === "James") {
 let maybe = "probably not"
 let feelingAmbitious = Math.random()
}
